---
- name: "Backup recovery 02"
  hosts: all
  gather_facts: false
  become: true

  vars_files:
    - vars/global.yml
    - vars/private.yml

  tasks:
    - name: create copr group
      group: name=copr gid=986

    - name: create copr user
      user: name=copr group=copr uid=989

    - name: install packages
      dnf:
        state: present
        name:
          - tmux
          - vim
          - htop
          - dstat
