---
- name: "raid"
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/global.yml
    - vars/private.yml

  vars:
    ansible_python_interpreter: /usr/bin/python3
    volume_size: 12288
    instance_name: copr-backend-backup-test-raid-10
    copr_instance_tag: devel

  tasks:
    - name: create test raid 10 instance
      amazon.aws.ec2_instance:
        region: us-east-1
        name: "{{ instance_name }}"
        key_name: "{{ aws_ssh_key }}"
        count: 1
        image_id: "{{ aws_images.f37 }}"
        instance_type: t3a.xlarge
        detailed_monitoring: true
        network:
          assign_public_ip: true
        vpc_subnet_id: "{{ infra_subnet }}"
        security_group: copr-gluster-node
        wait: true
        tags:
          FedoraGroup: copr
          CoprPurpose: storage
          CoprInstance: "{{ copr_instance_tag }}"

        volumes:
          - ebs:
              volume_size: "{{ volume_size }}"
              delete_on_termination: false
              volume_type: st1
            device_name: /dev/sdf
          - ebs:
              volume_size: "{{ volume_size }}"
              delete_on_termination: false
              volume_type: st1
            device_name: /dev/sdg
          - ebs:
              volume_size: "{{ volume_size }}"
              delete_on_termination: false
              volume_type: st1
            device_name: /dev/sdh
          - ebs:
              volume_size: "{{ volume_size }}"
              delete_on_termination: false
              # 3/4 disks are st1 but this must be sc1 otherwise we get:
              #   You have exceeded your maximum st1 storage limit of 50 TiB
              #   in this region. Please contact AWS Support to request an
              #   Elastic Block Store service limit increase.
              volume_type: sc1
            device_name: /dev/sdi

          #- ebs:
          #    volume_size: "{{ volume_size }}"
          #    delete_on_termination: true
          #    volume_type: sc1
          #  device_name: /dev/sdj
          #- ebs:
          #    volume_size: "{{ volume_size }}"
          #    delete_on_termination: true
          #    volume_type: sc1
          #  device_name: /dev/sdk
          #- ebs:
          #    volume_size: "{{ volume_size }}"
          #    delete_on_termination: true
          #    volume_type: sc1
          #  device_name: /dev/sdl
          #- ebs:
          #    volume_size: "{{ volume_size }}"
          #    delete_on_termination: true
          #    volume_type: sc1
          #  device_name: /dev/sdm
          #- ebs:
          #    volume_size: "{{ volume_size }}"
          #    delete_on_termination: true
          #    volume_type: sc1
          #  device_name: /dev/sdn
          #- ebs:
          #    volume_size: "{{ volume_size }}"
          #    delete_on_termination: true
          #    volume_type: sc1
          #  device_name: /dev/sdo
