---
- name: "testik-wrapper"
  hosts: localhost
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3

    old_device: eni-02715c9c35970acd0
    new_device: eni-04c3423cfeaaf95b3
    old_instance_id: i-0e5a4e4d7b819eef9
    new_instance_id: i-00de608ab4b835a1e

    ipv6: 2600:1f18:8ee:ae00:6c8c:e094:1c5b:c2f9
    ipv4: 18.208.10.131
    volumes:
      sdd: vol-0d281163265d9fee1
      sde: vol-038cfd4444cdc6b62
      sdf: vol-0f496f1335a663ea9
      sdg: vol-03a6faed4e610604c

  tasks:
    # - name: disassociate ipv6
    #   amazon.aws.ec2_eni:
    #     eni_id: "{{ old_device }}"
    #     ipv6_addresses: []
    #     state: present

    - name: disassociate an elastic IP with a device
      community.aws.ec2_eip:
        device_id: "{{ old_device }}"
        ip: "{{ ipv4 }}"
        in_vpc: true
        state: absent

    - name: associate an elastic IP with a device
      community.aws.ec2_eip:
        device_id: "{{ new_device }}"
        ip: "{{ ipv4 }}"
        in_vpc: true
        state: present

    - name: attach volumes to the new instance
      amazon.aws.ec2_vol:
        instance: "{{ new_instance_id }}"
        id: "{{ item.value }}"
        device_name: "{{ item.key }}"
      loop: "{{ volumes | dict2items }}"
